Repository Azure/draft, pull requests merged in 2018-05, with the labels that each got.

#758 use strings.TrimSuffix instead of strings.Replace
  pkg/builder/azure/builder.go
  pkg/builder/azure/builder_test.go
Labels: area/client, bug

#756 Add Chocolatey and GoFish to the quickstart docs
  docs/quickstart.md
Labels: area/docs

#755 feat(docs): add examples and tutorials page
  docs/README.md
  docs/examples-and-tutorials.md
  docs/quickstart.md
Labels: area/docs

#761 add link to Microsoft's Open Source Code of Conduct
  code-of-conduct.md
Labels: area/community, area/docs

#751 fix linter suggestion
  cmd/draft/connect.go
Labels: refactor

#783 remove upx from hacking docs
  docs/contributing/hacking.md
Labels: area/docs

#792 WIP: Fix circle memory issues
  .circleci/deploy-azure.sh
  Makefile
Labels: area/CI, wip

#795 Add testing for chartname update from #790
  pkg/draft/pack/create_test.go
Labels: area/tests
