Repository Azure/draft, pull requests merged in 2022-11, with the labels that each got.

#161 release for draft info and other fixes
  CHANGELOG.md
Labels: release 🎊🚀

#162 Fix badge for release.
  README.md
Labels: bug

#163 fix action version.
  .github/workflows/release-and-publish.yml
Labels: enhancement

#165 add examples support for draft info
  .github/workflows/e2e-info.yml
  .github/workflows/integration-info.yml
  .gitignore
  Makefile
  README.md
  cmd/info.go
  pkg/config/draftconfig.go
  template/dockerfiles/clojure/draft.yaml
  template/dockerfiles/csharp/draft.yaml
  template/dockerfiles/erlang/draft.yaml
  template/dockerfiles/go/draft.yaml
  template/dockerfiles/gomodule/draft.yaml
  template/dockerfiles/gradle/draft.yaml
  template/dockerfiles/java/draft.yaml
  template/dockerfiles/javascript/draft.yaml
  template/dockerfiles/php/draft.yaml
  template/dockerfiles/python/draft.yaml
  template/dockerfiles/ruby/draft.yaml
  template/dockerfiles/rust/draft.yaml
  template/dockerfiles/swift/draft.yaml
  test/check_info_schema.sh
  test/info.json
  test/info_schema.json
Labels: enhancement
