Repository Azure/draft, pull requests merged in 2023-07, with the labels that each got.

#220 update readme for supported flags
  README.md
Labels: documentation

#219 retry releases to get tag name
  .github/workflows/integration-install.yml
  scripts/install.sh
Labels: bug

#218 changes to support gradle wrapper and defaults
  cmd/create.go
  pkg/languages/defaults/gradle.go
  pkg/languages/defaults/gradle_test.go
  pkg/languages/defaults/testdata/sample.gradle
  pkg/languages/languages.go
  template/dockerfiles/gradlew/.dockerignore
  template/dockerfiles/gradlew/Dockerfile
  template/dockerfiles/gradlew/draft.yaml
Labels: enhancement

#217 changes for python file entry point detection
  .github/workflows/integration-linux.yml
  cmd/create.go
  cmd/create_test.go
  pkg/languages/defaults/python.go
  pkg/languages/defaults/python_test.go
  pkg/languages/languages.go
  template/dockerfiles/python/Dockerfile
  template/dockerfiles/python/draft.yaml
  test/gen_integration.sh
Labels: enhancement
