Repository Azure/draft, pull requests merged in 2024-12, with the labels that each got.

#434 az cli client cleanup
  cmd/setupgh.go
  cmd/setupgh_test.go
  pkg/prompts/prompts.go
  pkg/providers/az-client.go
  pkg/providers/azcli.go
  pkg/providers/azcli_test.go
  pkg/providers/azure.go
  pkg/providers/commandrunner.go
  pkg/providers/ghcli.go
  test/gen_integration.sh
  test/integration_config.json
Labels: enhancement

#443 New Draft Release v0.17.0 to avoid go sumdb collisions
  CHANGELOG.md
Labels: release 🎊🚀

#450 no dependabot groups they didnt work
  .github/dependabot.yml
Labels: dependencies

#445 reusable workflow for linux integrations
  .github/workflows/integration-linux.yml
  .github/workflows/integration-per-language.yml
  .github/workflows/integrations-linux.yml
  Makefile
  test/gen_integration.sh
  test/integration/go/helm.yaml
  test/integration/go/kustomize.yaml
  test/integration/go/manifest.yaml
  test/integration_config.json
Labels: enhancement
