Repository Azure/draft, pull requests merged in 2024-08, with the labels that each got.

#367 Release v0.0.38
  CHANGELOG.md
Labels: release 🎊🚀

#360 Migrating the helm deployments to Go templates
  pkg/deployments/deployments.go
  pkg/deployments/deployments_test.go
  template/deployments/helm/charts/Chart.yaml
  template/deployments/helm/charts/production.yaml
  template/deployments/helm/charts/templates/_helpers.tpl
  template/deployments/helm/charts/templates/deployment.yaml
  template/deployments/helm/charts/templates/service.yaml
  template/deployments/helm/charts/values.yaml
  template/deployments/kustomize/base/deployment.yaml
  template/deployments/kustomize/base/namespace.yaml
  template/deployments/kustomize/base/service.yaml
  template/deployments/kustomize/overlays/production/deployment.yaml
  template/deployments/kustomize/overlays/production/kustomization.yaml
  template/deployments/kustomize/overlays/production/service.yaml
  template/deployments/manifests/manifests/deployment.yaml
  template/deployments/manifests/manifests/service.yaml
Labels: enhancement

#372 Fix ACR and cluster resource group env var in workflow template
  template/azurePipelines/kustomize/.pipelines/azure-kubernetes-service.yaml
Labels: bug, enhancement
