Repository Azure/draft, pull requests merged in 2025-02, with the labels that each got.

#488 Scan workflows for unpinned GitHub Actions.
  .github/dependabot.yml
Labels: github_actions

#496 Release v0.17.4
  CHANGELOG.md
Labels: release 🎊🚀

#507 update to reflect homebrew core tap
  README.md
Labels: documentation
